server:
  http2:
    enabled: true
  port: ${SERVER_PORT:@im-message.server.port@}

spring:
  application:
    name: im-message
  profiles:
    active: @app.profiles.active@
  jackson:
    default-property-inclusion: non_null
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:im-lazy-init-config.yml
  cloud: # nacos
    sentinel:
      eager: true
      transport:
        dashboard: @sentinel.dashboard.url@
    nacos:
      discovery: # 服务注册发现
        server-addr: @nacos.config.server-addr@
        username: @nacos.discovery.username@
        password: @nacos.discovery.password@
        namespace: @nacos.discovery.namespace@
        group: @nacos.discovery.group@
      config: # 配置中心
        enabled: true
        server-addr: @nacos.config.server-addr@
        namespace: @nacos.config.namespace@
        group: @nacos.config.group@
        file-extension: @nacos.config.file-extension@
        preference: @nacos.config.preference@

dubbo: # dubbo
  scan:
    base-packages: com.xy.lucky.rpc.api
  application:
    serialize-check-status: WARN
  protocol: # dubbo协议
    name: dubbo
    port: -1
  consumer:
    retries: 3
    check: true
    timeout: 5000
  provider:
    delay: -1
    timeout: 5000
  registry: # 注册到nacos
    address: nacos://@nacos.config.server-addr@
    register-mode: instance
    group: @nacos.discovery.group@
    username: @nacos.discovery.username@
    password: @nacos.discovery.password@

# seata 配置
seata:
  enabled: false
  # 数据源代理模式
  data-source-proxy-mode: AT
  application-id: ${spring.application.name}
  config:
    type: nacos
    nacos:
      server-addr: @nacos.config.server-addr@
      namespace: @seata.config.namespace@
      group: @seata.config.group@
      username: @nacos.discovery.username@
      password: @nacos.discovery.password@
      data-id: @seata.config.data.id@
  # 事务组名称
  tx-service-group: default_tx_group
  # 注册seata
  registry:
    type: nacos
    nacos:
      server-addr: @nacos.discovery.server-addr@
      application: seata-server
      group: @seata.config.group@
      namespace: @seata.config.namespace@
      username: @nacos.discovery.username@
      password: @nacos.discovery.password@
  client:
    rm:
      # 是否上报成功状态
      report-success-enable: true

message:
  dispatch:
    max-retry: 3
    retry-delay-ms: 1000
    worker-size: 4
    confirm-timeout-ms: 5000
    confirm-timeout-check-interval-ms: 1000
    retry-wheel:
      tick-ms: 100
      slots: 512
  alert:
    baseline:
      min-connection-count: 1
      max-consumer-backlog: 2000
      min-success-rate: 0.99
      max-retry-rate: 0.05
      max-p99-ms: 300
